// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Entry struct {
	ID          int32          `json:"id"`
	Title       sql.NullString `json:"title"`
	Message     sql.NullString `json:"message"`
	Mood        []string       `json:"mood"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	CountryCode sql.NullInt32  `json:"country_code"`
}
