// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	DeleteEntry(ctx context.Context, id int32) (int32, error)
	GetEntry(ctx context.Context, id int32) (Entry, error)
	ListEntries(ctx context.Context) ([]Entry, error)
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error)
}

var _ Querier = (*Queries)(nil)
